- h5p-bildetema-topic-list/src/abstracts/_index.scss
- h5p-bildetema-topic-list/src/index.scss
- h5p-bildetema-topic-view/src/abstracts/_index.scss
- h5p-bildetema-topic-view/src/index.scss
- h5p-bildetema/src/abstracts/_index.scss
- h5p-bildetema/src/index.scss
add @forward instead of @use to _index.scss
> fix for "feature/add-abstracts-for-styling"

- .github/workflows/storybook.yaml
Be mindfull og the current directory
> build storybook path snafus

- common/types/types.ts
- h5p-bildetema-words-grid-view/src/components/Word/Word.stories.tsx
- h5p-bildetema-words-grid-view/src/components/Word/Word.tsx
- h5p-bildetema-words-grid-view/src/components/WordAudio/WordAudio.stories.tsx
- h5p-bildetema-words-grid-view/src/components/WordAudio/WordAudio.tsx
This PR is intentionally unstyled
> audio support

- common/abstracts/_variables.scss
- h5p-bildetema/src/components/Bildetema/Bildetema.module.scss
Orange focus effect around active elements when tabbing through them.
> Focus effect

- h5p-bildetema/package-lock.json
- h5p-bildetema/package.json
- h5p-bildetema/src/components/Bildetema/Bildetema.tsx
- h5p-bildetema/src/components/Breadcrumbs/Breadcrumbs.stories.tsx
- h5p-bildetema/src/components/Breadcrumbs/Breadcrumbs.test.tsx
- h5p-bildetema/src/components/Breadcrumbs/Breadcrumbs.tsx
- h5p-bildetema/src/components/Icons/Icons.tsx
- h5p-bildetema/src/components/TopicGrid/TopicGrid.tsx
- to simplify breadcrumbs management a "use-react-router-breadcrumbs" package was used
- some additional minor refactoring was conducted
> Update breadcrumbs to use HashRouter

- common/abstracts/_variables.scss
- common/types/types.ts
- common/utils/data.utils.ts
- h5p-bildetema/library.json
- h5p-bildetema/src/components/Bildetema/Bildetema.tsx
- h5p-bildetema/src/components/Breadcrumbs/Breadcrumbs.module.scss
- h5p-bildetema/src/components/Header/Header.module.scss
- h5p-bildetema/src/components/Header/Header.stories.tsx
- h5p-bildetema/src/components/Header/Header.tsx
- h5p-bildetema/src/components/Icons/Icons.tsx
- h5p-bildetema/src/components/TopicGrid/TopicGrid.module.scss
- h5p-bildetema/src/components/TopicGrid/TopicGrid.stories.tsx
- h5p-bildetema/src/components/TopicGrid/TopicGrid.tsx
- h5p-bildetema/src/components/TopicGridElement/TopicGridElement.module.scss
- h5p-bildetema/src/components/TopicGridElement/TopicGridElement.stories.tsx
- h5p-bildetema/src/components/TopicGridElement/TopicGridElement.tsx
- h5p-bildetema/src/components/TopicSizeButtons/TopicSizeButtons.module.scss
- h5p-bildetema/src/components/TopicSizeButtons/TopicSizeButtons.stories.tsx
- h5p-bildetema/src/components/TopicSizeButtons/TopicSizeButtons.tsx
- h5p-bildetema/src/components/TopicsList/TopicsList.tsx
- h5p-bildetema/src/components/Words/Words.tsx
- h5p-bildetema/src/h5p/H5PWrapper.tsx
- h5p-bildetema/src/library.ts
- package-lock.json
- package.json
- display topics as cards with images in two different formats (views) - big and compact. 
- add buttons to change the layout of the grid (big / compact)
> topic images

- common/abstracts/_variables.scss
- h5p-bildetema/library.json
- h5p-bildetema/semantics.json
- h5p-bildetema/src/components/Footer/Footer.module.scss
- h5p-bildetema/src/components/Footer/Footer.tsx
- h5p-bildetema/src/library.ts
- h5p-bildetema/src/semantics.ts
- h5p-bildetema/src/types/TranslationKey.ts
update the footer based on the comments from the customer
> footer update

- Dockerfile
- h5p-bildetema-words-grid-view/library.json
- h5p-bildetema-words-grid-view/package-lock.json
- h5p-bildetema-words-grid-view/package.json
- h5p-bildetema-words-grid-view/semantics.json
- h5p-bildetema-words-grid-view/src/h5p/H5PWrapper.tsx
- h5p-bildetema-words-grid-view/src/library.ts
- h5p-bildetema-words-grid-view/src/semantics.ts
- h5p-bildetema/library.json
- h5p-bildetema/package-lock.json
- h5p-bildetema/package.json
- h5p-bildetema/semantics.json
- h5p-bildetema/src/components/Words/Words.tsx
- h5p-bildetema/src/library.ts
- package-lock.json
- package.json
Instead of destroying and rebuilding the entire React app every time
parts of the params change.
> use events to trigger updates to grid view

- h5p-bildetema/src/components/Bildetema/Bildetema.stories.tsx
- h5p-bildetema/src/components/Breadcrumbs/Breadcrumbs.tsx
- h5p-bildetema/src/components/LanguageDropdown/LanguageDropdown.stories.tsx
- h5p-bildetema/src/components/LanguageSelector/LanguageSelector.stories.tsx
- h5p-bildetema/src/components/LanguageSelector/LanguageSelector.tsx
- h5p-bildetema/src/components/LanguageSelectorElement/LanguageSelectorElement.stories.tsx
- h5p-bildetema/src/components/TopicGrid/TopicGrid.stories.tsx
- h5p-bildetema/src/components/TopicGrid/TopicGrid.tsx
- h5p-bildetema/src/components/TopicGridElement/TopicGridElement.stories.tsx
- h5p-bildetema/src/components/TopicGridElement/TopicGridElement.tsx
- Refactor breadcrumbs
- Add missing props to storybook
> Fix missing component props in storybook

- common/abstracts/_variables.scss
- h5p-bildetema-words-grid-view/library.json
- h5p-bildetema-words-grid-view/src/library.ts
- h5p-bildetema-words-topic-image/library.json
- h5p-bildetema-words-topic-image/src/library.ts
- h5p-bildetema/library.json
- h5p-bildetema/src/components/Bildetema/Bildetema.tsx
- h5p-bildetema/src/components/Header/Header.module.scss
- h5p-bildetema/src/components/Header/Header.stories.tsx
- h5p-bildetema/src/components/Header/Header.tsx
- h5p-bildetema/src/components/SubHeader/SubHeader.module.scss
- h5p-bildetema/src/components/SubHeader/SubHeader.stories.tsx
- h5p-bildetema/src/components/SubHeader/SubHeader.tsx
- h5p-bildetema/src/library.ts
- h5p-editor-bildetema-words-topic-image/library.json
- h5p-editor-bildetema-words-topic-image/src/library.ts
- Making header sticky
- Separating header content and bottom content (bottom content now in SubHeader)
- Adding underline for the active language in the header
> Make header sticky

- h5p-bildetema/library.json
- h5p-bildetema/src/components/TopicGridElement/TopicGridElement.module.scss
- h5p-bildetema/src/library.ts
Fix for when word wrapping happens in topicCard
Avoiding:
> Make background always fill topicCard

- common/abstracts/_variables.scss
- h5p-bildetema-words-grid-view/library.json
- h5p-bildetema-words-grid-view/src/library.ts
- h5p-bildetema-words-topic-image/library.json
- h5p-bildetema-words-topic-image/src/library.ts
- h5p-bildetema/library.json
- h5p-bildetema/src/components/Bildetema/Bildetema.tsx
- h5p-bildetema/src/components/RouteController/RouteController.tsx
- h5p-bildetema/src/components/TopicGrid/TopicGrid.stories.tsx
- h5p-bildetema/src/components/TopicGrid/TopicGrid.tsx
- h5p-bildetema/src/library.ts
- h5p-editor-bildetema-words-topic-image/library.json
- h5p-editor-bildetema-words-topic-image/src/library.ts
Added the useEffect in TopicGrid to avoid being triggered when changing language (will still be triggered by changing favLanguages though).
> Add scroll to top

- h5p-bildetema/language/.en.json
- h5p-bildetema/language/nb.json
- h5p-bildetema/language/nn.json
- h5p-bildetema/library.json
- h5p-bildetema/semantics.json
- h5p-bildetema/src/components/Breadcrumbs/Breadcrumbs.module.scss
- h5p-bildetema/src/components/Breadcrumbs/Breadcrumbs.test.tsx
- h5p-bildetema/src/components/Breadcrumbs/Breadcrumbs.tsx
- h5p-bildetema/src/components/Icons/Icons.tsx
- h5p-bildetema/src/components/SubHeader/SubHeader.module.scss
- h5p-bildetema/src/library.ts
- h5p-bildetema/src/semantics.ts
Updating label and adding a home icon in the breadcrumb when not on homepage
> Change breadcrumb label

- h5p-bildetema-words-topic-image/library.json
- h5p-bildetema-words-topic-image/src/App.tsx
- h5p-bildetema-words-topic-image/src/components/TopicImageWordAudio/TopicImageWordAudio.module.scss
- h5p-bildetema-words-topic-image/src/h5p/H5PWrapper.tsx
- h5p-bildetema-words-topic-image/src/library.ts
- h5p-bildetema/library.json
- h5p-bildetema/src/components/Words/Words.tsx
- h5p-bildetema/src/library.ts
Make word list update when the language is changed. Will also only show the words that have a hotspot on the image.
> Change language in topic image

- h5p-bildetema-words-tree-view/library.json
- h5p-bildetema-words-tree-view/package-lock.json
- h5p-bildetema-words-tree-view/package.json
- h5p-bildetema-words-tree-view/src/library.ts
The packages are installed in root
> Uninstall vite related packages

- h5p-bildetema/library.json
- h5p-bildetema/src/components/Breadcrumbs/Breadcrumbs.module.scss
- h5p-bildetema/src/components/Breadcrumbs/Breadcrumbs.test.tsx
- h5p-bildetema/src/components/Breadcrumbs/Breadcrumbs.tsx
- h5p-bildetema/src/library.ts
Make sure that there is always an h1 element
> Use h1 on current page label

- h5p-bildetema/library.json
- h5p-bildetema/src/components/LanguageFavorites/LanguageFavorites.module.scss
- h5p-bildetema/src/library.ts
> Make languageFavorites follow site margin on print

- h5p-bildetema/library.json
- h5p-bildetema/src/components/Header/Header.module.scss
- h5p-bildetema/src/library.ts
> Make home link in header not have underline

- common/abstracts/_mixins.scss
- common/abstracts/_variables.scss
- h5p-bildetema-words-grid-view/library.json
- h5p-bildetema-words-grid-view/src/library.ts
- h5p-bildetema-words-topic-image/library.json
- h5p-bildetema-words-topic-image/src/library.ts
- h5p-bildetema/library.json
- h5p-bildetema/src/components/Header/Header.module.scss
- h5p-bildetema/src/components/LanguageFavorites/LanguageFavorites.module.scss
- h5p-bildetema/src/components/LanguageSelector/LanguageSelector.module.scss
- h5p-bildetema/src/components/TopicGrid/TopicGrid.module.scss
- h5p-bildetema/src/components/TopicGridElement/TopicGridElement.module.scss
- h5p-bildetema/src/library.ts
- h5p-editor-bildetema-words-topic-image/library.json
- h5p-editor-bildetema-words-topic-image/src/components/TopicChooser/TopicChooser.module.scss
- h5p-editor-bildetema-words-topic-image/src/library.ts
And create breakpoints and breakpoint mixin
> Make topic list images smaller on mobile

- h5p-bildetema/library.json
- h5p-bildetema/src/components/Header/Header.module.scss
- h5p-bildetema/src/components/LanguageDropdown/LanguageDropdown.module.scss
- h5p-bildetema/src/library.ts
Also removes languageMenuButton classes from Header since it is not used there, but used in LanguageDropdown instead
> Show active language on print when scaled down

- common/abstracts/_mixins.scss
- h5p-bildetema-words-grid-view/library.json
- h5p-bildetema-words-grid-view/src/library.ts
- h5p-bildetema-words-topic-image/library.json
- h5p-bildetema-words-topic-image/src/library.ts
- h5p-bildetema/library.json
- h5p-bildetema/src/components/Header/Header.module.scss
- h5p-bildetema/src/components/LanguageFavorites/LanguageFavorites.module.scss
- h5p-bildetema/src/library.ts
- h5p-editor-bildetema-words-topic-image/library.json
- h5p-editor-bildetema-words-topic-image/src/library.ts
When print was based on small screen width the print would not load
> Fix print not loading on small screen

- h5p-bildetema/library.json
- h5p-bildetema/src/components/TopicGrid/TopicGrid.module.scss
- h5p-bildetema/src/components/TopicGrid/TopicGrid.tsx
- h5p-bildetema/src/library.ts
> Make big topicGridElements the same size

- common/abstracts/_variables.scss
- h5p-bildetema-words-grid-view/library.json
- h5p-bildetema-words-grid-view/src/library.ts
- h5p-bildetema-words-topic-image/library.json
- h5p-bildetema-words-topic-image/src/library.ts
- h5p-bildetema/library.json
- h5p-bildetema/src/components/LanguageFavorites/LanguageFavorites.module.scss
- h5p-bildetema/src/library.ts
- h5p-editor-bildetema-words-topic-image/library.json
- h5p-editor-bildetema-words-topic-image/src/library.ts
Make sure that the TopicSizeButtons does not go over language favorites when active or focused
> Fix z-index values

- h5p-editor-bildetema-words-topic-image/src/components/Circle/Circle.tsx
- h5p-editor-bildetema-words-topic-image/src/components/Polygon/Polygon.tsx
- h5p-editor-bildetema-words-topic-image/src/components/Shape/Shape.tsx
- h5p-editor-bildetema-words-topic-image/src/components/Svg/Svg.tsx
- h5p-editor-bildetema-words-topic-image/src/components/editor/Editor.tsx
Before, only a click on Polygons would start edit mode
> fix: click to edit Circles

- common/abstracts/_variables.scss
- h5p-bildetema-words-grid-view/library.json
- h5p-bildetema-words-grid-view/src/library.ts
- h5p-bildetema-words-topic-image/library.json
- h5p-bildetema-words-topic-image/src/components/TopicImageContainer/TopicImageContainer.module.scss
- h5p-bildetema-words-topic-image/src/components/TopicImageWordAudio/TopicImageWordAudio.module.scss
- h5p-bildetema-words-topic-image/src/library.ts
- h5p-bildetema/library.json
- h5p-bildetema/src/components/Bildetema/Bildetema.module.scss
- h5p-bildetema/src/components/Footer/Footer.module.scss
- h5p-bildetema/src/components/Header/Header.module.scss
- h5p-bildetema/src/components/LanguageDropdown/LanguageDropdown.module.scss
- h5p-bildetema/src/components/Toggle/Toggle.module.scss
- h5p-bildetema/src/library.ts
- h5p-editor-bildetema-words-topic-image/library.json
- h5p-editor-bildetema-words-topic-image/src/library.ts
Ensure contrast ratio of at least 3:1 between outline and background (WCAG 2.0)
> Change outline focus color on light background

- h5p-bildetema/library.json
- h5p-bildetema/src/components/Breadcrumbs/Breadcrumbs.module.scss
- h5p-bildetema/src/components/PrintButton/PrintButton.module.scss
- h5p-bildetema/src/components/Toggle/Toggle.module.scss
- h5p-bildetema/src/library.ts
Minor fix to keep breadcrumbs and tools the same height always (not jumping up and down between pages)
> Fix tools height

- h5p-bildetema/library.json
- h5p-bildetema/src/components/Header/Header.module.scss
- h5p-bildetema/src/components/Header/Header.tsx
- h5p-bildetema/src/components/LanguageDropdown/LanguageDropdown.module.scss
- h5p-bildetema/src/components/LanguageFavorites/LanguageFavorites.module.scss
- h5p-bildetema/src/library.ts
> Make header smaller for smaller screens

- h5p-bildetema/library.json
- h5p-bildetema/src/components/PrintButton/PrintButton.module.scss
- h5p-bildetema/src/components/PrintButton/PrintButton.tsx
- h5p-bildetema/src/library.ts
Fix active state not appearing correct on ios device
> Add own useState to detect active print button

- .github/workflows/check-license.yml
- package-lock.json
- package.json
> Added license checker

- h5p-bildetema-words-grid-view/library.json
- h5p-bildetema-words-grid-view/src/library.ts
- h5p-bildetema-words-topic-image/library.json
- h5p-bildetema-words-topic-image/src/library.ts
- h5p-bildetema/library.json
- h5p-bildetema/src/library.ts
- h5p-editor-bildetema-words-topic-image/library.json
- h5p-editor-bildetema-words-topic-image/src/library.ts
In order to check if WordPress get updated
> Bump patch versions

- h5p-bildetema-words-grid-view/src/library.ts
- h5p-bildetema-words-topic-image/src/library.ts
- h5p-bildetema/library.json
- h5p-bildetema/src/components/Words/Words.tsx
- h5p-bildetema/src/library.ts
- h5p-bildetema/src/utils/router/router.utils.ts
- h5p-editor-bildetema-words-topic-image/src/library.ts
Fix bug where it is not possible to add topic image to a topic without a subtopic
> fix bug with topic image

- h5p-bildetema/library.json
- h5p-bildetema/src/components/Breadcrumbs/Breadcrumbs.tsx
- h5p-bildetema/src/components/Header/Header.tsx
- h5p-bildetema/src/components/LanguageFavorites/LanguageFavorites.tsx
- h5p-bildetema/src/components/SubHeader/SubHeader.module.scss
- h5p-bildetema/src/library.ts
And use flex wrap on subHeaderThemes
> Place keys correct

- h5p-bildetema/library.json
- h5p-bildetema/src/components/Breadcrumbs/Breadcrumbs.module.scss
- h5p-bildetema/src/components/Checkbox/Checkbox.module.scss
- h5p-bildetema/src/components/Checkbox/Checkbox.tsx
- h5p-bildetema/src/components/Header/Header.module.scss
- h5p-bildetema/src/components/Icons/Icons.tsx
- h5p-bildetema/src/components/LanguageDropdown/LanguageDropdown.module.scss
- h5p-bildetema/src/components/LanguageDropdown/LanguageDropdown.tsx
- h5p-bildetema/src/components/PrintButton/PrintButton.module.scss
- h5p-bildetema/src/components/PrintButton/PrintButton.tsx
- h5p-bildetema/src/components/TopicSizeButtons/TopicSizeButtons.module.scss
- h5p-bildetema/src/library.ts
Make the icons scale together with the font-size when only font-size is scaled (not normal zoom)
> Make icons more responsive when text size changes

- h5p-bildetema-words-grid-view/library.json
- h5p-bildetema-words-grid-view/src/components/Word/Word.tsx
- h5p-bildetema-words-grid-view/src/library.ts
> Avoid duplicate id values

- h5p-bildetema/src/hooks/useSiteLanguage.ts
The name is up for debate. Use like this:
```tsx
export const MyComponent = () => {
const lang = useSiteLanguage();
return <span lang={lang}>Heihei</span>;
};
```
> feat: `useSiteLanguage` hook

- h5p-bildetema/language/.en.json
- h5p-bildetema/language/da.json
- h5p-bildetema/language/is.json
- h5p-bildetema/language/nb.json
- h5p-bildetema/language/nn.json
- h5p-bildetema/language/sv.json
- h5p-bildetema/library.json
- h5p-bildetema/semantics.json
- h5p-bildetema/src/components/LanguageSelector/LanguageSelector.module.scss
- h5p-bildetema/src/components/LanguageSelector/LanguageSelector.tsx
- h5p-bildetema/src/library.ts
- h5p-bildetema/src/semantics.ts
- h5p-bildetema/src/types/TranslationKey.ts
Question/follow up
- Can we use &#039; in semantics? Else we need to change the english translation that this pr adds
> Add link to old Bildetema in language selector

- h5p-bildetema/library.json
- h5p-bildetema/semantics.json
- h5p-bildetema/src/library.ts
- h5p-bildetema/src/semantics.ts
Forgot to update the semantics files when changing the english translation
> Add updated english translation to semantics

- h5p-bildetema/library.json
- h5p-bildetema/src/components/Footer/Footer.tsx
- h5p-bildetema/src/components/LanguageSelector/LanguageSelector.tsx
- h5p-bildetema/src/library.ts
- h5p-bildetema/src/utils/url.utils.ts
H5P Text field turned `&` into `&amp;`
> Add URL filter

- h5p-bildetema/library.json
- h5p-bildetema/src/components/LanguageSelector/LanguageSelector.tsx
- h5p-bildetema/src/library.ts
prevent languageselector to crash when it receives a language that does not exist in languagesOriginal
> Fix language selector

- package-lock.json
Audit npm packages to resolve `CVE-2023-37466` (vm2 Sandbox Escape vulnerability).
> fix: CVE-2023-37466

- common/package.json
- common/utils/data.utils.ts
- h5p-bildetema-words-grid-view/package.json
- h5p-bildetema-words-topic-image/package.json
- h5p-bildetema/package.json
- h5p-bildetema/src/components/Bildetema/Bildetema.tsx
- h5p-bildetema/src/components/Header/Header.tsx
- h5p-bildetema/src/components/LanguageDropdown/LanguageDropdown.tsx
- h5p-bildetema/src/components/Logos/Logos.tsx
- h5p-bildetema/src/components/Words/Words.tsx
- h5p-editor-bildetema-words-topic-image/package.json
- h5p-editor-bildetema-words-topic-image/src/h5p/ChooseTopicH5PWrapper.tsx
- h5p-editor-bildetema-words-topic-image/src/h5p/H5PWrapper.tsx
- h5p-editor-bildetema-words-topic-image/src/types/Fields.ts
Needs to be reviewed, especially the handling of 'unexpected any'
> build: set ESlint warnings to zero

- h5p-bildetema/language/.en.json
- h5p-bildetema/language/da.json
- h5p-bildetema/language/is.json
- h5p-bildetema/language/nb.json
- h5p-bildetema/language/nn.json
- h5p-bildetema/language/sv.json
- h5p-bildetema/library.json
- h5p-bildetema/semantics.json
- h5p-bildetema/semantics.json.d.ts
- h5p-bildetema/src/components/Footer/Footer.tsx
- h5p-bildetema/src/components/LanguageSelector/LanguageSelector.tsx
Removes link to old Bildetema in language selector and footer.
> feat: remove old Bildetema links

- h5p-bildetema/library.json
- h5p-bildetema/src/components/SearchPage/SearchPage.tsx
- h5p-bildetema/src/components/SearchPage/SearchView/SearchView.module.scss
- h5p-bildetema/src/components/SearchPage/SearchView/SearchView.tsx
- h5p-bildetema/src/components/Select/Select.module.scss
setViewLanguage() updates the value, but it doesn't update in view before next frame. So, I passed it through to findWords(), but we could do it differently. 
This updates the results right away when one of the language changes, the search value it still the same.
> feat: add view language selector

- common/hooks/useMyCollections.ts
- common/package.json
- common/types/types.ts
- h5p-bildetema-words-grid-view/library.json
- h5p-bildetema-words-topic-image/library.json
- h5p-bildetema/library.json
- h5p-bildetema/src/components/CollectionsController/CollectionController.tsx
- h5p-bildetema/src/components/CollectionsController/CollectionElement/CollectionElement.tsx
- h5p-bildetema/src/components/CollectionsController/CollectionPage/CollectionPage.tsx
- h5p-bildetema/src/components/CollectionsController/CollectionsPage/CollectionsPage.tsx
- h5p-bildetema/src/components/SearchPage/ChooseCollectionDialog/ChooseCollectionDialog.tsx
- h5p-bildetema/src/components/SearchPage/SearchResultView/SearchResultView.tsx
- h5p-bildetema/src/components/Select/Select.tsx
- h5p-editor-bildetema-words-topic-image/library.json
- package-lock.json
✅ Can now add collections with the same name
[Trello-412](https://trello.com/c/wD4EYlGU/412-legge-til-id-for-samlinger)
> Use id to identify a collection insted of title

- h5p-bildetema-words-grid-view/language/.en.json
- h5p-bildetema-words-grid-view/language/nb.json
- h5p-bildetema-words-grid-view/library.json
- h5p-bildetema-words-grid-view/library.json.d.ts
- h5p-bildetema-words-grid-view/semantics.json
- h5p-bildetema-words-grid-view/semantics.json.d.ts
- h5p-bildetema-words-grid-view/src/components/Word/Word.tsx
- h5p-bildetema-words-topic-image/library.json
- h5p-bildetema/language/.en.json
- h5p-bildetema/language/da.json
- h5p-bildetema/language/is.json
- h5p-bildetema/language/nb.json
- h5p-bildetema/language/nn.json
- h5p-bildetema/language/sv.json
- h5p-bildetema/library.json
- h5p-bildetema/semantics.json
- h5p-bildetema/semantics.json.d.ts
- h5p-bildetema/src/components/CollectionsController/CollectionElement/CollectionElement.tsx
- h5p-bildetema/src/components/CollectionsController/MultiLanguageWord/MultiLanguageWord.tsx
- h5p-bildetema/src/components/SearchPage/SearchResultCard/SearchResultCard.tsx
- h5p-editor-bildetema-words-topic-image/library.json
- h5p-editor-bildetema-words-topic-image/library.json.d.ts
✅ add aria labels for more options (MoreVertIcon) and BookMarkIcon
✅ add translations for aria labels
[Trello-439](https://trello.com/c/Xm9JLDf2/439-g%C3%A5-over-aria-tekster-og-sjekke-tilgjengelighet)
> add aria labels for more options icon and bookmark

- h5p-bildetema/language/.en.json
- h5p-bildetema/language/da.json
- h5p-bildetema/language/is.json
- h5p-bildetema/language/nb.json
- h5p-bildetema/language/nn.json
- h5p-bildetema/language/sv.json
- h5p-bildetema/library.json
- h5p-bildetema/semantics.json
- h5p-bildetema/semantics.json.d.ts
- h5p-bildetema/src/components/CollectionsController/CollectionsPage/CollectionsPage.module.scss
- h5p-bildetema/src/components/CollectionsController/CollectionsPage/CollectionsPage.tsx
- h5p-bildetema/src/components/Header/Header.tsx
> feat: update my collections translations

- common/constants/search-only-words.ts
- h5p-bildetema-words-grid-view/library.json
- h5p-bildetema-words-grid-view/library.json.d.ts
- h5p-bildetema-words-topic-image/library.json
- h5p-bildetema/language/.en.json
- h5p-bildetema/language/da.json
- h5p-bildetema/language/is.json
- h5p-bildetema/language/nb.json
- h5p-bildetema/language/nn.json
- h5p-bildetema/language/sv.json
- h5p-bildetema/library.json
- h5p-bildetema/semantics.json
- h5p-bildetema/semantics.json.d.ts
- h5p-bildetema/src/components/Footer/Footer.tsx
- h5p-editor-bildetema-words-topic-image/library.json
- h5p-editor-bildetema-words-topic-image/library.json.d.ts
> feat: update translations and copyright

- common/components/CheckboxItem/CheckboxItem.tsx
- common/components/ChooseCollectionsDialog/ChooseCollectionsDialog.tsx
- common/components/ConfirmationDialog/ConfirmationDialog.tsx
- common/components/Dialog/Dialog.tsx
- common/hooks/useCollectionDialog.ts
- h5p-bildetema-words-grid-view/library.json
- h5p-bildetema-words-grid-view/library.json.d.ts
- h5p-bildetema-words-topic-image/library.json
- h5p-bildetema/language/da.json
- h5p-bildetema/language/is.json
- h5p-bildetema/language/nb.json
- h5p-bildetema/language/nn.json
- h5p-bildetema/language/sv.json
- h5p-bildetema/library.json
- h5p-editor-bildetema-words-topic-image/library.json
- h5p-editor-bildetema-words-topic-image/library.json.d.ts
> feat: update translations sv and is

- h5p-bildetema-words-grid-view/library.json
- h5p-bildetema-words-grid-view/library.json.d.ts
- h5p-bildetema-words-grid-view/src/components/Word/Word.module.scss
- h5p-bildetema/library.json
- h5p-bildetema/src/components/PrintButton/PrintButton.tsx
- h5p-bildetema/src/components/PrintWords/PrintWords.module.scss
- h5p-bildetema/src/components/PrintWords/PrintWords.tsx
- h5p-bildetema/src/components/SearchPage/SearchPage.module.scss
- h5p-bildetema/src/components/SearchPage/SearchResultCard/SearchResultCard.module.scss
- h5p-bildetema/src/components/SearchPage/SearchResultView/SearchResultView.module.scss
> fix: print on mobile

- h5p-bildetema/src/components/PrintWords/PrintWords.tsx
Changes image size from "medium" to "xlarge" on print
> fix: image quality on print

- h5p-bildetema/library.json
- h5p-bildetema/src/components/CollectionsController/CollectionController.tsx
- h5p-bildetema/src/components/CollectionsController/CollectionPage/CollectionPage.tsx
- h5p-bildetema/src/components/CollectionsController/MultiLanguageWord/MultiLanguageWord.module.scss
- h5p-bildetema/src/components/SearchPage/SearchResultCard/SearchResultCard.module.scss
- h5p-bildetema/src/components/SubHeader/SubHeader.tsx
> fix: improve collection editing

- h5p-bildetema/library.json
- h5p-bildetema/src/components/Bildetema/Bildetema.tsx
- h5p-bildetema/src/components/Breadcrumbs/Breadcrumbs.tsx
- package-lock.json
- package.json
Changes the title in head when navigating between pages in app
> feat: change title in head
