Tietoevry-Create/h5p-bildetema

.github/dependabot.yml
We don't want them to create new releases anyways
=> Label dependabot PRs as `non-functional`

.github/workflows/h5p_bildetema_check-library-version.yml, h5p-bildetema/README.md
This PR adds a custom message for the `h5p-bildetema` sub-project. This helps with two things:
- The custom messages makes it easier to guess which project was or wasn't updated
- The new `project-id` setting makes it possible for the action to edit the correct messages when new commits are added
=> Customise h5p-bildetema library update message

h5p-bildetema-words-grid-view/src/components/Word/Word.module.scss
Based on case with "Gummistøvler" text alignment and line height.
=> Add text-align center to word label in grid

h5p-bildetema/package-lock.json, h5p-bildetema/package.json, h5p-bildetema/semantics.json, h5p-bildetema/src/components/Header/Header.tsx, h5p-bildetema/src/constants/languages.ts, h5p-bildetema/src/hooks/useL10n.ts, h5p-bildetema/src/library.ts, h5p-bildetema/src/semantics.ts, h5p-bildetema/src/types/TranslationKey.ts
We will be placing the languages a bit more sophisticated in the future, but I think its nice to have a starting point. Also, like this, we get to try out the new `useL10ns` hook. Yell out if anything seems off. The code for it is found here: https://github.com/Tietoevry-Create/use-h5p/blob/v1.1.0/src/hooks/useLocalizations.ts
=> Translate more texts

common/types/Point.ts, common/types/ThemeImageHotspot.ts, h5p-bildetema-words-theme-image/semantics.json, h5p-bildetema-words-theme-image/src/h5p/H5PWrapper.tsx, h5p-bildetema-words-theme-image/src/semantics.ts, h5p-bildetema-words-theme-image/tsconfig.json
This PR adds an initial semantics structure for `h5p-bildetema-words-theme-image`, which will be used in its editor widget.
It also populates the content type initializer's `Params` type with an equivalent type structure.
I'm not totally sold on the `hotspot` name, suggestions are welcome. Also, if there are fields that are missing, please shout.
=> Initialize semantics structure for theme image

h5p-bildetema/src/components/Breadcrumbs/Breadcrumbs.module.scss, h5p-bildetema/src/components/Breadcrumbs/Breadcrumbs.tsx
Prettier for some reason triggers on `Breadcrumbs.tsx`, even though there are no formatting issues there. Trying to fix it by touching the file.
=> do insignificant change to fix format issues

package.json
`npm run docker:build`: Builds a docker image with the tag `h5p-bildetema`
`npm run docker:run` runs the docker image with the tag `h5p-bildetema`
`npm run docker:run-no-logs` runs the image in detached mode and hides logs from standard output
=> Add scripts for building and running docker

.github/workflows/h5p-bildetema-words-grid-view_release.yml, .github/workflows/h5p-bildetema-words-topic-image_release.yml, .github/workflows/h5p-editor-bildetema-words-topic-image_release.yml, .github/workflows/h5p_bildetema_release.yml
We can't create a new release only if there's a version change because
we don't at this point know what was the previous version.
=> Tag release with updated version

h5p-bildetema-words-topic-image/library.json, h5p-bildetema-words-topic-image/src/components/TopicImageSVG/TopicImageSVG.module.scss, h5p-bildetema-words-topic-image/src/library.ts
Since we have a max height set we need to make the width: "auto" instead of 100% to avoid images being stretched out
=> Fix width of square svg topic images

h5p-bildetema/library.json, h5p-bildetema/src/components/Bildetema/Bildetema.module.scss, h5p-bildetema/src/components/Header/Header.module.scss, h5p-bildetema/src/library.ts
In devdev, languages who are not the active language has an underline. Only the active language should have underline
=> Fix correct underline for languages in header

h5p-bildetema/library.json, h5p-bildetema/src/components/Icons/Icons.tsx, h5p-bildetema/src/components/TopicSizeButtons/TopicSizeButtons.module.scss, h5p-bildetema/src/library.ts
TopicSizeButtons appeared like this on mobile:
Trying to fix it with this pr
=> Fix topic size buttons on mobile

common/base/_fonts.scss, h5p-bildetema-words-grid-view/library.json, h5p-bildetema-words-grid-view/src/library.ts, h5p-bildetema-words-topic-image/library.json, h5p-bildetema-words-topic-image/src/library.ts, h5p-bildetema/library.json, h5p-bildetema/src/components/Bildetema/Bildetema.tsx, h5p-bildetema/src/components/RouteController/RouteController.tsx, h5p-bildetema/src/library.ts, h5p-editor-bildetema-words-topic-image/library.json, h5p-editor-bildetema-words-topic-image/src/library.ts
- Override WordPress font family
- Make "Loading"-label smaller
- Make "Page does not exist"-label similar to "Loading"-label
=> Override WordPress font family

h5p-bildetema/src/components/TopicGrid/TopicGrid.module.scss, h5p-bildetema/src/components/TopicGrid/TopicGrid.tsx
Use whichever solution you prefer. With this, we end up always having the placeholders in the DOM, however we don't need to do the calculation in JS.
=> Use CSS to show/hide placeholder grid elements

h5p-bildetema/library.json, h5p-bildetema/src/components/Icons/Icons.tsx, h5p-bildetema/src/components/LanguageDropdown/LanguageDropdown.module.scss, h5p-bildetema/src/components/LanguageSelectorElement/LanguageSelectorElement.module.scss, h5p-bildetema/src/library.ts
- Move transform attributes from svg to path, since svg is not allowed to have transform attributes in SVG 1.1 and Safari does not support it for SVG 2 either
- Make sure languageDropdown has relative position, was not positioning correctly in Safari
=> Fix language selector in Safari

h5p-bildetema/library.json, h5p-bildetema/src/components/Checkbox/Checkbox.module.scss, h5p-bildetema/src/components/Icons/Icons.tsx, h5p-bildetema/src/components/LanguageSelectorElement/LanguageSelectorElement.module.scss, h5p-bildetema/src/library.ts
and small fixes in language selector
- Centering star-icons with previously used height and width
- Setting a line-height for when language text is on two lines
=> Fix home icon css

h5p-bildetema-words-topic-image/library.json, h5p-bildetema-words-topic-image/src/components/TopicImageSVG/TopicImageSVG.tsx, h5p-bildetema-words-topic-image/src/library.ts
Make sure aspect ratio is preserved and align the svg overlay to the top left corner
=> Preserve aspect ratio of svg overlay in Safari/iOS

h5p-bildetema-words-grid-view/library.json, h5p-bildetema-words-grid-view/src/components/TopicWordsGrid/TopicWordsGrid.tsx, h5p-bildetema-words-grid-view/src/library.ts
When starting at any other page than the grid image page and navigation to a grid image page, the show words toggle will not work. Seems like we don't need the hack created for show words, since the showWrittenWords value is always correct (when I have tested at least).
=> Fix show words in Safari

h5p-bildetema/library.json, h5p-bildetema/src/components/Checkbox/Checkbox.module.scss, h5p-bildetema/src/components/Checkbox/Checkbox.tsx, h5p-bildetema/src/library.ts
Focus does not work on elements that are hidden. Make the checkbox hidden for the eye only by unsetting styling, and keep other functionalities.
=> Make star focusable

h5p-bildetema/library.json, h5p-bildetema/src/components/Breadcrumbs/Breadcrumbs.module.scss, h5p-bildetema/src/library.ts
Since both breakpoint-min and breakpoint-max was used, devices with a width of 768 came in between these sizes and got a different appearance
=> Fix breadcrumbs for 768 width devices

h5p-bildetema-words-grid-view/library.json, h5p-bildetema-words-grid-view/src/components/TopicWordsGrid/TopicWordsGrid.module.scss, h5p-bildetema-words-grid-view/src/components/TopicWordsGrid/TopicWordsGrid.tsx, h5p-bildetema-words-grid-view/src/components/Word/Word.tsx, h5p-bildetema-words-grid-view/src/components/WordAudio/WordAudio.module.scss, h5p-bildetema-words-grid-view/src/components/WordAudio/WordAudio.tsx, h5p-bildetema-words-grid-view/src/library.ts, h5p-bildetema/library.json, h5p-bildetema/src/components/Bildetema/Bildetema.tsx, h5p-bildetema/src/components/Breadcrumbs/Breadcrumbs.module.scss, h5p-bildetema/src/components/Breadcrumbs/Breadcrumbs.test.tsx, h5p-bildetema/src/components/Breadcrumbs/Breadcrumbs.tsx, h5p-bildetema/src/components/Header/Header.module.scss, h5p-bildetema/src/components/Header/Header.tsx, h5p-bildetema/src/components/LanguageFavorites/LanguageFavorites.module.scss, h5p-bildetema/src/components/LanguageFavorites/LanguageFavorites.tsx, h5p-bildetema/src/components/LanguageSelector/LanguageSelector.module.scss, h5p-bildetema/src/components/LanguageSelector/LanguageSelector.tsx, h5p-bildetema/src/components/LanguageSelectorElement/LanguageSelectorElement.module.scss, h5p-bildetema/src/components/LanguageSelectorElement/LanguageSelectorElement.tsx, h5p-bildetema/src/components/TopicGrid/TopicGrid.module.scss, h5p-bildetema/src/components/TopicGrid/TopicGrid.tsx, h5p-bildetema/src/components/TopicGridElement/TopicGridElement.module.scss, h5p-bildetema/src/components/TopicGridElement/TopicGridElement.tsx, h5p-bildetema/src/library.ts
- Topics and words are now within a `ul`, making it easier for user to know that these elements are related to each other and how many there are.
- Topic titles and word labels now within an `h2` (not necessary, to be discussed)
- Breadcrumbs are now within an `ol` and `nav` to be more organized and highlight that these are navigational links.
- Languages (favorites and selector) are now placed within an `ul` and `nav` making it easier for user to know that this is a section and how many items it contains, and that these are navigational links.
=> Make site more accessible

h5p-bildetema/library.json, h5p-bildetema/src/components/Header/Header.module.scss, h5p-bildetema/src/components/Header/Header.tsx, h5p-bildetema/src/components/TopicGridElementAudio/TopicGridElementAudio.module.scss, h5p-bildetema/src/library.ts
Now that languages is placed inside a `nav`, hide that one instead of the language (ul) element
=> Hide nav in header on small screens

h5p-bildetema/language/.en.json, h5p-bildetema/language/nb.json, h5p-bildetema/language/nn.json, h5p-bildetema/library.json, h5p-bildetema/semantics.json, h5p-bildetema/src/components/Footer/Footer.tsx, h5p-bildetema/src/library.ts, h5p-bildetema/src/semantics.ts, h5p-bildetema/src/types/TranslationKey.ts
If the page is not added to an environment or language, we should provide an ok 404-page. But perhaps the default url should be "/om-bildetema" and not in english "/about-bildetema"
=> Add about link in footer

h5p-bildetema/library.json, h5p-bildetema/src/components/Bildetema/Bildetema.tsx, h5p-bildetema/src/library.ts
Could be good to keep it for localhost (not only displaying the url as the page name) but we don't need it for WordPress. There it will be better to actually use the page name and be able to change it.
=> Avoid overriding document title when not necessary

common/abstracts/_variables.scss, h5p-bildetema-words-grid-view/library.json, h5p-bildetema-words-grid-view/src/components/WordAudio/WordAudio.module.scss, h5p-bildetema-words-grid-view/src/library.ts, h5p-bildetema-words-topic-image/library.json, h5p-bildetema-words-topic-image/src/components/TopicImageWordAudio/TopicImageWordAudio.module.scss, h5p-bildetema-words-topic-image/src/library.ts, h5p-bildetema/library.json, h5p-bildetema/src/components/Breadcrumbs/Breadcrumbs.module.scss, h5p-bildetema/src/components/Checkbox/Checkbox.module.scss, h5p-bildetema/src/components/Footer/Footer.module.scss, h5p-bildetema/src/components/Header/Header.module.scss, h5p-bildetema/src/components/LanguageSelectorElement/LanguageSelectorElement.module.scss, h5p-bildetema/src/components/PrintButton/PrintButton.module.scss, h5p-bildetema/src/components/Toggle/Toggle.module.scss, h5p-bildetema/src/components/TopicGridElement/TopicGridElement.module.scss, h5p-bildetema/src/components/TopicSizeButtons/TopicSizeButtons.module.scss, h5p-bildetema/src/library.ts, h5p-editor-bildetema-words-topic-image/library.json, h5p-editor-bildetema-words-topic-image/src/library.ts
Avoid getting blue font color on hover, blue box-shadow on focus etc, when previewing the H5P in WordPress:
=> Make sure styling is not overrided by WordPress

h5p-bildetema-words-topic-image/library.json, h5p-bildetema-words-topic-image/src/components/TopicImageContainer/TopicImageContainer.module.scss, h5p-bildetema-words-topic-image/src/components/TopicImageSVG/TopicImageSVG.module.scss, h5p-bildetema-words-topic-image/src/components/TopicImageWordList/TopicImageWordList.module.scss, h5p-bildetema-words-topic-image/src/library.ts
Provides a bigger image on mobile that can use the whole screen width instead of a tiny image that is difficult to tap on
=> Move topic image above word list on mobile

h5p-bildetema/library.json, h5p-bildetema/src/components/Header/Header.tsx, h5p-bildetema/src/components/LanguageDropdown/LanguageDropdown.stories.tsx, h5p-bildetema/src/components/LanguageDropdown/LanguageDropdown.tsx, h5p-bildetema/src/components/PrintButton/PrintButton.tsx, h5p-bildetema/src/library.ts
When using keyboard to navigate and opening a dropdown, it kept open even though the user did not focus on the elements in the dropdown anymore. The dropdown had to be closed manually.
=> Close dropdowns when not focused on

h5p-bildetema-words-topic-image/library.json, h5p-bildetema-words-topic-image/src/components/TopicImageSVG/TopicImageSVG.module.scss, h5p-bildetema-words-topic-image/src/library.ts
Fix for all browsers
also changes the breakpoint for the max-height from small to medium, since that is when the shift actually happens in the header
=> Fix topic image img height

h5p-bildetema/library.json, h5p-bildetema/src/components/Bildetema/Bildetema.tsx, h5p-bildetema/src/components/Breadcrumbs/Breadcrumbs.tsx, h5p-bildetema/src/components/PrintButton/PrintButton.tsx, h5p-bildetema/src/components/Toggle/Toggle.tsx, h5p-bildetema/src/components/TopicSizeButtons/TopicSizeButtons.tsx, h5p-bildetema/src/hooks/useCurrentLanguage.ts, h5p-bildetema/src/hooks/useSiteLanguage.ts, h5p-bildetema/src/library.ts
The lang attributes was interfering with the new aria-labels that was not in the "current language" but the main language of the page.
This pr moves the "current language" attribute from main content/body to routes and breadcrumbs. Tools (toggle, print and topicSizeButtons) will now inherit from the html lang instead.
=> Fix lang attribute placement

h5p-bildetema/library.json, h5p-bildetema/src/components/LanguageDropdown/LanguageDropdown.module.scss, h5p-bildetema/src/components/LanguageDropdown/LanguageDropdown.tsx, h5p-bildetema/src/components/PrintButton/PrintButton.module.scss, h5p-bildetema/src/components/PrintButton/PrintButton.tsx, h5p-bildetema/src/library.ts
Noticed two places where the visually-hidden was used, that it did work properly in Safari. Both of these instances used visually-hidden for the button label and only on smaller screens. 
When on a laptop (or large screen) and sizing the browser window down to the breakpoint, the labels are hidden but the size of the button is not adjusted before the mouse hoveres over the button (language button) or it does not get adjusted at all (print button). 
Seems safer to use `display: none` for these instances.
=> Fix some visually hidden not working in Safari

common/abstracts/_variables.scss, h5p-bildetema-words-grid-view/library.json, h5p-bildetema-words-grid-view/src/library.ts, h5p-bildetema-words-topic-image/library.json, h5p-bildetema-words-topic-image/src/library.ts, h5p-bildetema/library.json, h5p-bildetema/src/components/Checkbox/Checkbox.module.scss, h5p-bildetema/src/components/Checkbox/Checkbox.tsx, h5p-bildetema/src/library.ts, h5p-editor-bildetema-words-topic-image/library.json, h5p-editor-bildetema-words-topic-image/src/library.ts
Fix errors:
- Empty form label (checkbox labels)
- Very low contrast (grey disabled color)
Was noticed when using WAVE Evaluation Tool (Chrome extension) and having the language selector open.
=> Fix label and contrast error in language selector

h5p-bildetema/library.json, h5p-bildetema/src/components/LanguageSelector/LanguageSelector.tsx, h5p-bildetema/src/components/LanguageSelectorElement/LanguageSelectorElement.stories.tsx, h5p-bildetema/src/components/LanguageSelectorElement/LanguageSelectorElement.tsx
Sort the languages in the language selector alphabetically for each chosen language. Currently the placement from the db is used on all languages.
=> feat: sort languages alphabetically

.github/dependabot.yml
Dependabot is smart enough to check all packages in a monorepo.
=> ci: check only root package for dependency updates

h5p-bildetema/library.json, h5p-bildetema/src/components/Bildetema/Bildetema.tsx, h5p-bildetema/src/components/Header/Header.tsx, h5p-bildetema/src/components/LanguageFavorites/LanguageFavorites.tsx, h5p-bildetema/src/utils/language.utils.ts
Fixes "TypeError: Cannot read properties of undefined (reading 'localeCompare')" when trying to compare a language in favLanguages that are not in the database anymore. Example: when we changed the Filipino language code the old code could still be saved for some users - resulting in this TypeError.
It also ensures that no "old" languages will be shown for the user, and that the userData.favoriteLanguages will not store those languages anymore.
=> Fix: typeerror and add filter to favLanguages

h5p-bildetema-words-topic-image/library.json, h5p-bildetema-words-topic-image/semantics.json, h5p-bildetema-words-topic-image/semantics.json.d.ts
Fixes TypeError when editing Topic Images in Wordpress. Word.labels was not stored since semantics didn't have updated field values for it.
If new Topic Images are created now, words will only have `id` and `images` and no `label` or `labels`. This means we have to add a check for this in `Editor.tsx` or `extractWordLabel` since these words will not have `label` or `labels` until they are updated in the useEffect of `Editor.tsx `. PR that can fix this in `extractWordLabel` https://github.com/Tietoevry-Create/h5p-bildetema/pull/1157
=> fix: add missing fields in topic image semantics

h5p-bildetema/library.json, h5p-bildetema/src/components/Words/Words.tsx
Currently the grid is always rendered even though `onlyTopicImage` is set to true. This PR ensures that is it not rendered when it doesn't have to be.
The PR is difficult to test since `H5PAllContents` in `setViewInstances` does not work in localhost (getting all the topic images created in Wordpress), and no topic images will therefore be shown. But to explain the code: 
In order to get the actual value of the topic's `onlyTopicImage` property initially in `setViewInstances`, the `if (!isTopicImageView) return false;` in the `onlyTopicImage` useMemo needed to be removed. Then we could check `onlyTopicImage` to know if grid view should be rendered. The display class then only need to be set based on the value of `showTopicImageView`.
=> fix: only render words-grid-view when needed

common/package.json, common/utils/library/library.utils.ts, h5p-bildetema-words-topic-image/src/h5p/H5PWrapper.tsx, package-lock.json
This version does not bring anything new to the table and everything _should_ work as before.
The reason for updating is mostly to see that the new version does not break anything in Bildetema (thus probably not breaking anything anywhere else either).
=> chore: install h5p-types v5.1.0

h5p-bildetema/src/components/CollectionsController/MultiLanguageWord/MultiLanguageWord.module.scss, h5p-bildetema/src/components/CollectionsController/MultiLanguageWord/MultiLanguageWord.tsx, h5p-bildetema/src/components/SearchPage/SearchResultCard/SearchResultCard.module.scss, h5p-bildetema/src/components/SearchPage/SearchResultCard/SearchResultCard.tsx
- Only shows the translation label when one language is displayed in search results and collections
- Makes the translation label font-size smaller
- Makes a bit more padding around the translations
=> fix: search result translation label

h5p-bildetema/library.json, h5p-bildetema/src/components/Button/Button.module.scss, h5p-bildetema/src/components/Button/Button.tsx, h5p-bildetema/src/components/SearchPage/SearchFilter/SearchFilterDialog.module.scss, h5p-bildetema/src/components/SearchPage/SearchFilter/SearchFilterDialog.tsx, h5p-bildetema/src/components/SearchPage/SearchInput/SearchInput.module.scss, h5p-bildetema/src/components/SearchPage/SearchView/SearchView.module.scss, h5p-bildetema/src/components/SearchPage/SearchView/SearchView.tsx, h5p-bildetema/src/components/Select/Select.module.scss, h5p-bildetema/src/components/Select/Select.tsx
- Make the prefix for the view language select shorter when a language is selected
- Makes sure the filter button and view language select wraps under each other on small devices
- Makes sure the input field has a minimum width
- Handle overflow on buttons and selects if there are really long labels for some translations
- Makes the options for the selects a litte bit bigger
- Adds hover styling to filter dialog close button
=> fix: search page on mobile

h5p-bildetema-words-grid-view/src/index.tsx, h5p-bildetema-words-grid-view/src/types/Params.ts, h5p-bildetema-words-topic-image/semantics.json.d.ts, h5p-bildetema-words-topic-image/src/index.tsx, h5p-bildetema-words-topic-image/src/types/Params.ts, h5p-bildetema/src/index.tsx, h5p-bildetema/src/types/Params.ts, turbo.json
Move `semantics;` call to entry points to make sure that Vite picks them up and doesn't compile them away. By being part of the compile process, `unplugin-json-dts` will be able to generate types for semantics.
1. Check out the branch locally
1. Do a change to the `semantics.json` files
1. Build the project
1. See that changes affect `semantics.json.d.ts` files
=> build: generate types for semantics on build

h5p-bildetema/library.json, h5p-bildetema/src/components/CollectionsController/CollectionPage/CollectionPage.tsx
for environments that shouldn't display search
=> fix: remove search button link from empty collections

common/abstracts/_variables.scss, h5p-bildetema-words-grid-view/library.json, h5p-bildetema-words-grid-view/library.json.d.ts, h5p-bildetema-words-topic-image/library.json, h5p-bildetema/library.json, h5p-bildetema/src/components/CollectionsController/CollectionController.module.scss, h5p-bildetema/src/components/CollectionsController/CollectionElement/CollectionElement.module.scss, h5p-bildetema/src/components/CollectionsController/CollectionPage/CollectionPage.module.scss, h5p-bildetema/src/components/CollectionsController/CollectionsPage/CollectionsPage.module.scss, h5p-bildetema/src/components/CollectionsController/CollectionsPage/CollectionsPage.tsx, h5p-bildetema/src/components/Menu/Menu.module.scss, h5p-bildetema/src/components/SubHeader/SubHeader.tsx, h5p-bildetema/src/components/TopicRouteController/TopicRouteController.module.scss, h5p-bildetema/src/hooks/useCurrentCollection.ts, h5p-editor-bildetema-words-topic-image/library.json, h5p-editor-bildetema-words-topic-image/library.json.d.ts
- Makes the font-size larger and increases the line-height of the description on the collections page.
- Makes the (kebab) menu button on the collections dark (not negative with white icon on dark background) and makes the hover background more similar to the other beige variables used. 
- Adds breadcrumbs to the collections page. Was previously hidden, but make sense to include it as the collection pages do have it and there it includes "home" as the start page.
=> feat: collections page edits

common/utils/searchResults.utils.ts, h5p-bildetema-words-grid-view/library.json, h5p-bildetema-words-grid-view/library.json.d.ts, h5p-bildetema-words-topic-image/library.json, h5p-bildetema/library.json, h5p-editor-bildetema-words-topic-image/library.json, h5p-editor-bildetema-words-topic-image/library.json.d.ts
Changes the order of the search results. Words starting with the search term will be shown before words that ends with the search term.
Relates to Trello-issue: https://trello.com/c/z1CKejCr/452-s%C3%B8k-treff-virker-ikke-logisk
=> fix: change search result order

h5p-bildetema/language/.en.json, h5p-bildetema/language/da.json, h5p-bildetema/language/is.json, h5p-bildetema/language/nb.json, h5p-bildetema/language/nn.json, h5p-bildetema/language/sv.json, h5p-bildetema/semantics.json, h5p-bildetema/semantics.json.d.ts, h5p-bildetema/src/components/SearchPage/SearchFilter/SearchFilterDialog.module.scss, h5p-bildetema/src/components/SearchPage/SearchFilter/SearchFilterDialog.tsx
- Fixes issue with use of column-count in Firefox (better to use it on a parent element of the list than the actual list element)
- Adds a visually hidden label to the close button
- Adds a new translation for the close button and removes an unused translation
- Turns the parent element of the checkboxes into a unordered list, and the checkbox elements into list elements. This makes it more accessible for screen reader users. 
Related to Trello-card: https://trello.com/c/4zIsnXfn/453-filtrer-s%C3%B8k-firefox-p%C3%A5-mac
=> fix: topic filter in Firefox, and make filter more accessible

common/components/TextInput/TextInput.module.scss, h5p-bildetema-words-grid-view/library.json, h5p-bildetema-words-grid-view/library.json.d.ts, h5p-bildetema-words-topic-image/library.json, h5p-bildetema/language/.en.json, h5p-bildetema/language/da.json, h5p-bildetema/language/is.json, h5p-bildetema/language/nb.json, h5p-bildetema/language/nn.json, h5p-bildetema/language/sv.json, h5p-bildetema/library.json, h5p-bildetema/semantics.json, h5p-bildetema/semantics.json.d.ts, h5p-bildetema/src/components/Bildetema/Bildetema.tsx, h5p-bildetema/src/components/CollectionsController/CollectionElement/CollectionElement.tsx, h5p-bildetema/src/components/CollectionsController/CollectionPage/CollectionPage.module.scss, h5p-bildetema/src/components/CollectionsController/CollectionPage/CollectionPage.tsx, h5p-bildetema/src/components/Header/Header.tsx, h5p-editor-bildetema-words-topic-image/library.json, h5p-editor-bildetema-words-topic-image/library.json.d.ts
Need to make sure the font-family is set on the label element. Wordpress sometimes removes some of the styling that is set.
Also:
- Removes the bookmark from an empty collection (was used to describe how to add words to the collection)
- Adds status message when a link to a collection is copied (from the overview page of the collections)
- Adds status message when a collection name is changed
- Adds status message when a collection is deleted
- Make sure search will be visible when deployed to production. Previously it has been discussed to only deploy collections and wait with search, but now they both will be deployed at the same time.
=> fix: set font family for TextInput label

h5p-bildetema/library.json, h5p-bildetema/src/components/CollectionsController/CollectionsPage/CollectionsPage.tsx
Fixes issue with spacing in collection titles when copying the link, and makes sure the title is encoded. 
Related to comment: https://trello.com/c/JMxIVBko#comment-670689e108816825f4860e1b
=> fix: copy collection link encoding

common/constants/search-only-words.ts, common/utils/data.utils.ts, h5p-bildetema-words-grid-view/library.json, h5p-bildetema-words-grid-view/library.json.d.ts, h5p-bildetema-words-topic-image/library.json, h5p-bildetema/library.json, h5p-editor-bildetema-words-topic-image/library.json, h5p-editor-bildetema-words-topic-image/library.json.d.ts
Makes specific words hidden from the topic view. These words can now only be found via the search page (and added to collections from the search page). They will still be visible in collections as before.
=> feat: hide specific words from topic view

common/components/Audio/Audio.tsx, h5p-bildetema-words-grid-view/library.json, h5p-bildetema-words-grid-view/library.json.d.ts, h5p-bildetema-words-grid-view/src/components/WordAudio/WordAudio.tsx, h5p-bildetema-words-topic-image/library.json, h5p-bildetema-words-topic-image/src/components/TopicImageWordAudio/TopicImageWordAudio.tsx, h5p-bildetema/library.json, h5p-bildetema/src/components/TopicGridElementAudio/TopicGridElementAudio.tsx, h5p-editor-bildetema-words-topic-image/library.json, h5p-editor-bildetema-words-topic-image/library.json.d.ts
Fixing issue with old versions of audio files still being played in frontend even though new ones are added to Azure. New and old files use the same file name, and we therefore need to force a reload to make sure the browser plays the new audio file.
=> fix: force reload of audio

h5p-bildetema/language/nb.json, h5p-bildetema/language/nn.json, h5p-bildetema/library.json
Changes "Romanes" to "Vlax Romani" for Norwegian bokmål and nynorsk.
=> fix: rmy translations
